[build]
  publish = "."
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.iso"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Disposition = "attachment"